baseURL: "https://michaelbuhidar.com"
title: Michael Buhidar
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Michael Buhidar
  description: "My personal blog."
  keywords: [Blog, Portfolio, Linux, michaelbuhidar, Mike Buhidar, C64, Python, retro computing]
  author: Michael Buhidar
  images: ["https://avatars.githubusercontent.com/u/40150224?v=4"]
  DateFormat: "January 2, 2016"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    #disableHLJS: true # to disable highlight.js
    #disableFingerprinting: true
    favicon: "https://avatars.githubusercontent.com/u/40150224?v=4"
    favicon16x16: "https://avatars.githubusercontent.com/u/40150224?v=4"
    favicon32x32: "https://avatars.githubusercontent.com/u/40150224?v=4"
    apple_touch_icon: "https://avatars.githubusercontent.com/u/40150224?v=4"
    safari_pinned_tab: "https://avatars.githubusercontent.com/u/40150224?v=4"

  label:
    text: " "
    icon: "https://avatars.githubusercontent.com/u/40150224?v=4"
    iconHeight: 25

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Michael Buhidar 
    subtitle: "My personal blog."
    imageUrl: "https://avatars.githubusercontent.com/u/40150224?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: azra image
    buttons:
      - name: About Me
        url: about

  # home-info mode
  #homeInfoParams:
  #Title: "My personal blog."
  #Content: Hi there! I'm michaelbuhidar.

  socialIcons:
    - name: github
      url: "https://github.com/mbuhidar"
    - name: mastodon
      url: "https://hachyderm.io/@michaelbuhidar"
    - name: twitter
      url: "https://twitter.com/AzraMike"
    - name: linkedin
      url: "https://www.linkedin.com/in/michael-buhidar"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #Text: "Suggest Changes" # edit text
  #appendFilePath: true # to append file path to Edit link

  # Fuse.js search options
  # https://fusejs.io/api/options.html
  fuseOpts:
    # Basic Options
    isCaseSensitive: false
    includeScore: false
    includeMatches: false
    minMatchCharLength: 1
    shouldSort: true
    findAllMatches: false
    keys: ["title", "permalink", "summary", "content"]
    # Fuzzy Matching Options
    location: 0
    threshold: 0.6
    distance: 100
    ignoreLocation: false
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

# Enables search functionality via Fuse.js Basic
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
